services:
  proxy-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: n0vacore/claw-cli:v1.0.2
    container_name: proxy-agent
    network_mode: host
    environment:
      - AGENT_COMMAND=${AGENT_COMMAND:-agent}
    env_file:
      - path: .env
        required: false
    volumes:
      - /home/Hook/.cursor:/root/.cursor:rw
    restart: always
    command: ["uvicorn", "proxy_agent.app:app", "--host", "0.0.0.0", "--port", "8088"]
